### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Jinjin89** [Jinjin89/bioplus#1]
TODO list

- [ ] ena downloader with 1) ascp 2) wget 
- [ ] downlload with md5sum check
- [ ] shell script: get the file life time
